var trials = [
	{
		batch: 1,
		categ: 'social',
		column1: ['Japanese',	'Irish',	'Brazilian',	'Brazilian',	'German',	'Chinese',	'Irish',	'Cheerleader',	'Irish',	'Chinese',	'Parking Meter Attendant',	'Brazilian',	'Parking Meter Attendant',	'Brazilian',	'Brazilian',	'Mexican',	'Parking Meter Attendant',	'Mexican',	'Japanese',	'Australian',	'Australian',	'Brazilian',	'German',	'Mexican',	'Mexican',	'Australian',	'Australian',	'Japanese',	'Pharmacist',	'Parking Meter Attendant',	'German',	'Japanese',	'Brazilian',	'Cheerleader',	'Brazilian',	'Brazilian',	'Australian',	'Cheerleader',	'Lawyer',	'Chinese',	'Parking Meter Attendant',	'Musician',	'Musician',	'Cheerleader',	'Japanese',	'Australian',	'Lawyer',	'Irish',	'Irish',	'Japanese',	'Australian',	'Chinese',	'Chinese',	'Chinese',	'Lawyer',	'Moroccan',	'Musician',	'Parking Meter Attendant',	'Parking Meter Attendant',	'Cheerleader',	'Cheerleader',	'Lawyer',	'Brazilian',	'Brazilian',	'Parking Meter Attendant',	'German',	'Lawyer',	'Brazilian',	'Brazilian',	'Irish',	'Chinese',	'Australian',	'Australian',	'Australian',	'Brazilian',	'Brazilian',	'Cheerleader',	'Parking Meter Attendant',	'Parking Meter Attendant',	'Parking Meter Attendant',	'Australian',	'Parking Meter Attendant',	'Japanese',	'Brazilian',	'Moroccan',	'Parking Meter Attendant',	'Cheerleader',	'Japanese',	'Parking Meter Attendant',	'Parking Meter Attendant',	'Lawyer',	'Chinese',	'Parking Meter Attendant',	'Australian',	'Moroccan',	'Irish',	'Brazilian',	'Mexican',	'Irish',	'Moroccan',	'Moroccan',	'Australian',	'Parking Meter Attendant',	'German',	'Nurse',	'German',	'Cheerleader',	'Musician',	'Mexican',	'Australian',	'Lawyer',	'Parking Meter Attendant',	'Cheerleader',	'Australian'],
		column2: ['Musician',	'Moroccan',	'Mexican',	'Pharmacist',	'Politician',	'Police Officer',	'Japanese',	'Moroccan',	'Mexican',	'Mexican',	'Japanese',	'Moroccan',	'Chinese',	'Lawyer',	'Irish',	'Police Officer',	'Brazilian',	'Moroccan',	'Mexican',	'Nurse',	'Mexican',	'German',	'Mexican',	'Pharmacist',	'Musician',	'Cheerleader',	'Nurse',	'Pharmacist',	'Police Officer',	'Japanese',	'Police Officer',	'Nurse',	'Japanese',	'German',	'Moroccan',	'Chinese',	'Nurse',	'Mexican',	'Mexican',	'Lawyer',	'Mexican',	'Retail Clerk',	'Police Officer',	'Police Officer',	'Russian',	'Moroccan',	'Pharmacist',	'Nurse',	'Mexican',	'Mexican',	'Brazilian',	'Moroccan',	'Nurse',	'Pharmacist',	'Mexican',	'Musician',	'Retail Clerk',	'Politician',	'Irish',	'Rapper',	'Chinese',	'Musician',	'German',	'Cheerleader',	'Nurse',	'Pharmacist',	'Nurse',	'Chinese',	'Nurse',	'Mexican',	'Pharmacist',	'Lawyer',	'Rapper',	'Cheerleader',	'Politician',	'Chinese',	'Japanese',	'Chinese',	'Retail Clerk',	'Cheerleader',	'Lawyer',	'Mexican',	'Police Officer',	'Retail Clerk',	'Nurse',	'Japanese',	'Pharmacist',	'Nurse',	'Pharmacist',	'Lawyer',	'Mexican',	'Rapper',	'Japanese',	'Brazilian',	'Musician',	'German',	'Japanese',	'Pharmacist',	'Moroccan',	'Pharmacist',	'Pharmacist',	'Politician',	'Irish',	'Politician',	'Police Officer',	'Moroccan',	'Lawyer',	'Pharmacist',	'Moroccan',	'Lawyer',	'Moroccan',	'Politician',	'Irish',	'Cheerleader'],
		column3: ['Politician',	'Musician',	'Pharmacist',	'Police Officer',	'Retail Clerk',	'Russian',	'Nurse',	'Nurse',	'Police Officer',	'Russian',	'Pharmacist',	'Nurse',	'German',	'Retail Clerk',	'Moroccan',	'Retail Clerk',	'Chinese',	'Russian',	'Russian',	'Politician',	'Rapper',	'Pharmacist',	'Russian',	'South African',	'Nurse',	'Mexican',	'Retail Clerk',	'Politician',	'South African',	'Nurse',	'Politician',	'Rapper',	'Police Officer',	'Musician',	'Police Officer',	'Japanese',	'South African',	'Politician',	'Pharmacist',	'Politician',	'Russian',	'South African',	'South African',	'Retail Clerk',	'South African',	'Politician',	'South African',	'South African',	'South African',	'Politician',	'South African',	'Politician',	'Police Officer',	'Retail Clerk',	'Russian',	'Police Officer',	'Russian',	'Rapper',	'Nurse',	'Russian',	'Police Officer',	'Police Officer',	'Moroccan',	'Lawyer',	'Retail Clerk',	'Russian',	'Police Officer',	'Musician',	'Police Officer',	'Pharmacist',	'South African',	'South African',	'Russian',	'Russian',	'South African',	'Pharmacist',	'Mexican',	'Russian',	'South African',	'South African',	'Mexican',	'Police Officer',	'Retail Clerk',	'South African',	'Police Officer',	'German',	'Russian',	'Police Officer',	'Police Officer',	'Rapper',	'Rapper',	'South African',	'Lawyer',	'Lawyer',	'Retail Clerk',	'Mexican',	'Politician',	'Retail Clerk',	'Politician',	'Retail Clerk',	'Police Officer',	'Retail Clerk',	'Police Officer',	'South African',	'Politician',	'Rapper',	'Retail Clerk',	'Politician',	'Nurse',	'Police Officer',	'Russian',	'South African',	'Retail Clerk',	'Chinese']
	},
	{
		batch: 2,
		categ: 'anim',
		column1: ['FARM', 'OWL', 'CAVE',	'CAT',	'DESERT',	'CAT',	'CAVE',	'CIRCUS',	'CAT',	'CIRCUS',	'CAT',	'CIRCUS',	'CAT',	'CAT',	'CAVE',	'CAVE',	'CAT',	'CAT',	'CIRCUS',	'CAT',	'CAT',	'CAVE',	'CAT',	'CAVE',	'CAVE',	'CAT',	'CIRCUS',	'FARM',	'CAT',	'CAVE',	'RAT',	'CAT',	'CAVE',	'FARM',	'CAT',	'CIRCUS',	'FARM',	'CIRCUS',	'DESERT',	'CAT',	'CAVE',	'DESERT',	'DESERT',	'CAVE',	'CAT',	'OWL',	'PIG',	'CAVE',	'CIRCUS',	'PIG',	'FARM',	'CIRCUS',	'CAVE',	'CAT',	'CAT',	'CAVE',	'DESERT',	'CAVE',	'CAT',	'CAT',	'CIRCUS',	'CIRCUS',	'CAVE',	'CAT',	'CIRCUS',	'CIRCUS',	'OWL',	'CIRCUS',	'CAT',	'CAT',	'DESERT',	'FARM',	'CAT',	'OWL',	'OWL',	'CAT',	'DESERT',	'DESERT',	'CAVE',	'CAVE',	'CAT',	'CAVE',	'DESERT',	'FARM',	'CAT',	'CIRCUS',	'CAT',	'FARM',	'FARM',	'CIRCUS',	'DESERT',	'CIRCUS',	'CAVE',	'CAVE',	'FARM',	'CAVE',	'CAT',	'CIRCUS',	'CAT',	'CAT',	'CAVE',	'CIRCUS',	'DESERT',	'DESERT',	'CAT',	'DESERT',	'CAVE',	'CAVE',	'DESERT',	'CIRCUS',	'CAT',	'CAVE',	'DESERT',	'CAT',	'PIG',	'OWL',	'CIRCUS',	'CAT',	'CAVE',	'CAVE'],
		column2: ['PIG', 'PIG',	'CIRCUS',	'SAVANNA',	'RAT',	'PIG',	'FARM',	'FARM',	'CIRCUS',	'FARM',	'CIRCUS',	'OWL',	'OWL',	'CAVE',	'OWL',	'DESERT',	'DESERT',	'OWL',	'FARM',	'DESERT',	'FARM',	'FARM',	'RAT',	'PIG',	'SAVANNA',	'PIG',	'DESERT',	'PIG',	'FARM',	'PIG',	'SAVANNA',	'CIRCUS',	'CIRCUS',	'PIG',	'FARM',	'DESERT',	'OWL',	'RAT',	'FARM',	'DESERT',	'DESERT',	'OWL',	'OWL',	'RAT',	'CAVE',	'RAT',	'SAVANNA',	'CIRCUS',	'SAVANNA',	'RAT',	'RAT',	'RAT',	'FARM',	'CIRCUS',	'DESERT',	'FARM',	'PIG',	'PIG',	'PIG',	'DESERT',	'DESERT',	'DESERT',	'CIRCUS',	'CAVE',	'PIG',	'FARM',	'SAVANNA',	'OWL',	'CAVE',	'CAVE',	'SAVANNA',	'SAVANNA',	'OWL',	'PIG',	'PIG',	'CIRCUS',	'RAT',	'OWL',	'RAT',	'OWL',	'CAVE',	'OWL',	'FARM',	'OWL',	'FARM',	'PIG',	'CIRCUS',	'OWL',	'RAT',	'FARM',	'OWL',	'PIG',	'OWL',	'CIRCUS',	'OWL',	'CIRCUS',	'RAT',	'OWL',	'DESERT',	'CAVE',	'DESERT',	'OWL',	'PIG',	'FARM',	'OWL',	'PIG',	'DESERT',	'DESERT',	'FARM',	'DESERT',	'CIRCUS',	'DESERT',	'FARM',	'CAVE',	'RAT',	'RAT',	'DESERT',	'FARM',	'CIRCUS', 'FARM'],
		column3: ['RAT',	'RAT',	'FARM',	'SNAKE',	'SNAKE',	'SAVANNA',	'SNAKE',	'SNAKE',	'OWL',	'RAT',	'SAVANNA',	'PIG',	'SAVANNA',	'RAT',	'RAT',	'RAT',	'SAVANNA',	'RAT',	'PIG',	'FARM',	'SNAKE',	'OWL',	'SAVANNA',	'RAT',	'SNAKE',	'SNAKE',	'RAT',	'SAVANNA',	'SAVANNA',	'SAVANNA',	'SNAKE',	'SNAKE',	'SAVANNA',	'SNAKE',	'PIG',	'SAVANNA',	'SAVANNA',	'SAVANNA',	'PIG',	'RAT',	'FARM',	'PIG',	'SAVANNA',	'SNAKE',	'DESERT',	'SAVANNA',	'SNAKE',	'RAT',	'SNAKE',	'SAVANNA',	'SAVANNA',	'SNAKE',	'RAT',	'PIG',	'PIG',	'SAVANNA',	'RAT',	'SNAKE',	'RAT',	'SNAKE',	'PIG',	'FARM',	'DESERT',	'OWL',	'SNAKE',	'OWL',	'SNAKE',	'SNAKE',	'CIRCUS',	'PIG',	'SNAKE',	'SNAKE',	'PIG',	'SAVANNA',	'SNAKE',	'FARM',	'SAVANNA',	'SNAKE',	'SAVANNA',	'SAVANNA',	'SAVANNA',	'SNAKE',	'SAVANNA',	'RAT',	'OWL',	'RAT',	'DESERT',	'PIG',	'SNAKE',	'SAVANNA',	'RAT',	'SAVANNA',	'PIG',	'PIG',	'SNAKE',	'SNAKE',	'SNAKE',	'RAT',	'OWL',	'SNAKE',	'PIG',	'SAVANNA',	'SAVANNA',	'OWL',	'SNAKE',	'SNAKE',	'SNAKE',	'SAVANNA',	'RAT',	'SNAKE',	'RAT',	'OWL',	'SNAKE',	'FARM',	'SNAKE',	'SNAKE',	'OWL',	'RAT',	'OWL',	'PIG']
	}
	];